// Comprehensive list of 200+ cities across the world
export const CITIES = [
  // India (30 cities)
  "Bangalore, India",
  "Mumbai, India",
  "Delhi, India",
  "Hyderabad, India",
  "Pune, India",
  "Chennai, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Jaipur, India",
  "Lucknow, India",
  "Chandigarh, India",
  "Indore, India",
  "Kochi, India",
  "Visakhapatnam, India",
  "Surat, India",
  "Vadodara, India",
  "Nagpur, India",
  "Bhopal, India",
  "Coimbatore, India",
  "Gurgaon, India",
  "Noida, India",
  "Ghaziabad, India",
  "Faridabad, India",
  "Thane, India",
  "Navi Mumbai, India",
  "Nashik, India",
  "Aurangabad, India",
  "Amritsar, India",
  "Ludhiana, India",
  "Ranchi, India",

  // United States (40 cities)
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Boston, MA",
  "Miami, FL",
  "Atlanta, GA",
  "Portland, OR",
  "Las Vegas, NV",
  "Nashville, TN",
  "Detroit, MI",
  "Minneapolis, MN",
  "New Orleans, LA",
  "Memphis, TN",
  "Baltimore, MD",
  "Washington, DC",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Long Beach, CA",
  "Kansas City, MO",
  "Mesa, AZ",
  "Virginia Beach, VA",

  // Europe (50 cities)
  "London, United Kingdom",
  "Paris, France",
  "Berlin, Germany",
  "Madrid, Spain",
  "Rome, Italy",
  "Amsterdam, Netherlands",
  "Vienna, Austria",
  "Brussels, Belgium",
  "Prague, Czech Republic",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Lisbon, Portugal",
  "Dublin, Ireland",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Bern, Switzerland",
  "Athens, Greece",
  "Istanbul, Turkey",
  "Moscow, Russia",
  "St. Petersburg, Russia",
  "Kiev, Ukraine",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Belgrade, Serbia",
  "Zagreb, Croatia",
  "Ljubljana, Slovenia",
  "Bratislava, Slovakia",
  "Krakow, Poland",
  "Wroclaw, Poland",
  "Gdansk, Poland",
  "Munich, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Frankfurt, Germany",
  "Stuttgart, Germany",
  "Düsseldorf, Germany",
  "Lyon, France",
  "Marseille, France",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Milan, Italy",
  "Venice, Italy",
  "Florence, Italy",
  "Naples, Italy",
  "Turin, Italy",

  // United Kingdom (10 cities)
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Leeds, United Kingdom",
  "Glasgow, United Kingdom",
  "Edinburgh, United Kingdom",
  "Liverpool, United Kingdom",
  "Bristol, United Kingdom",
  "Sheffield, United Kingdom",
  "Newcastle, United Kingdom",
  "Nottingham, United Kingdom",

  // Asia (30 cities)
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Shanghai, China",
  "Beijing, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Hangzhou, China",
  "Chengdu, China",
  "Xi'an, China",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Singapore, Singapore",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Bali, Indonesia",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Hong Kong, Hong Kong",
  "Taipei, Taiwan",
  "Chiang Mai, Thailand",
  "Yangon, Myanmar",
  "Phnom Penh, Cambodia",
  "Vientiane, Laos",
  "Dhaka, Bangladesh",
  "Colombo, Sri Lanka",

  // Southeast Asia (15 cities)
  "Penang, Malaysia",
  "Johor Bahru, Malaysia",
  "Surabaya, Indonesia",
  "Bandung, Indonesia",
  "Medan, Indonesia",
  "Makassar, Indonesia",
  "Davao, Philippines",
  "Quezon City, Philippines",
  "Makati, Philippines",
  "Chiang Rai, Thailand",
  "Pattaya, Thailand",
  "Krabi, Thailand",
  "Da Nang, Vietnam",
  "Nha Trang, Vietnam",
  "Can Tho, Vietnam",

  // Australia (10 cities)
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Hobart, Australia",
  "Canberra, Australia",
  "Gold Coast, Australia",
  "Newcastle, Australia",
  "Wollongong, Australia",

  // Canada (10 cities)
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Ottawa, Canada",
  "Winnipeg, Canada",
  "Quebec City, Canada",
  "Hamilton, Canada",
  "Kitchener, Canada",

  // Middle East (10 cities)
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Baghdad, Iraq",

  // Africa (10 cities)
  "Cairo, Egypt",
  "Lagos, Nigeria",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "Accra, Ghana",
  "Casablanca, Morocco",
  "Tunis, Tunisia",
  "Addis Ababa, Ethiopia",
  "Dar es Salaam, Tanzania",

  // South America (10 cities)
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Brasília, Brazil",
  "Salvador, Brazil",
  "Fortaleza, Brazil",
  "Buenos Aires, Argentina",
  "Córdoba, Argentina",
  "Lima, Peru",
  "Bogotá, Colombia",
  "Medellín, Colombia",

  // Remote
  "Remote",
  "Hybrid",
]

export const COMPANY_TYPES = [
  "Startup (0-2 years)",
  "Early Stage Startup (2-5 years)",
  "Growth Stage (5-10 years)",
  "Mid-sized Company (100-1000 employees)",
  "Large Company (1000-10000 employees)",
  "Enterprise (10000+ employees)",
  "Multinational Corporation",
]

export const EDUCATION_QUALIFICATIONS = [
  "High School / GED",
  "Bachelor's Degree",
  "Master's Degree",
  "PhD / Doctorate",
  "Professional Certification",
  "No Specific Requirement",
]

export const WORK_MODES = [
  "On-site",
  "Hybrid",
  "Remote",
]

export const WORK_AUTHORIZATION_STATUS = [
  "Yes, I am a U.S. citizen",
  "Yes, I am a permanent resident (Green Card)",
  "Yes, I have an H-1B visa",
  "Yes, I have an L-1 visa",
  "Yes, I have an OPT/CPT/F-1 visa",
  "Yes, I have a TN visa",
  "Yes, I have an O-1 visa",
  "Yes, I have other work authorization",
  "No, I need sponsorship",
  "Prefer not to disclose",
]
