-- Insert test data from your Supabase table
INSERT INTO live_application_queue (
  id,
  user_id,
  job_id,
  first_name,
  last_name,
  email,
  gender,
  phone,
  country_code,
  location,
  headline,
  bio,
  resume_url,
  linkedin_url,
  github_url,
  veteran_status,
  disability_status,
  ethnicity,
  work_authorization_status,
  skills,
  top_skills,
  experience,
  education,
  certifications,
  achievements,
  job_preferences,
  work_mode_preferences,
  salary_currency,
  salary_min,
  salary_max,
  desired_roles,
  preferred_cities,
  work_professions,
  onboarding_data,
  company_name,
  job_title,
  job_url,
  status,
  created_at,
  cover_letter
) VALUES (
  'f758f088-265c-4f32-b232-3d0be523c7f8',
  'e454481c-b99f-4cad-b9f1-fa8d85d381f4',
  'S-098',
  'Aditya',
  'Surana',
  'mail.adityasurana@gmail.com',
  'male',
  '7776004343',
  NULL,
  'Delhi, India',
  'Founder & CEO at Nextquark',
  'Build this super cool App! Tinder for jobs',
  '1772580688339.pdf',
  'linkedin.com/profiles/adityasurana7',
  NULL,
  'I am not a protected veteran',
  'No, I do not have a disability',
  'Southeast Asian',
  NULL,
  ARRAY['JavaScript','TypeScript','React','React Native','Node.js','Docker','AWS','C++','REST APIs','Python'],
  ARRAY['JavaScript','TypeScript','React Native','AWS','Python'],
  '[
    {
      "id": "1772580824689",
      "title": "AI Engineering Intern",
      "skills": ["Python", "NLP", "Predictive Analysis", "Alteryx"],
      "company": "S&P Global",
      "endDate": "Aug 2024",
      "workMode": "Onsite",
      "isCurrent": false,
      "startDate": "May 2024",
      "description": "I worked closely with the internal audit team building there internal dashboard to provide data driven insights.",
      "jobLocation": "Hyderabad, Telangana, India",
      "employmentType": "Internship"
    },
    {
      "id": "1772580912421",
      "title": "Builder",
      "skills": ["Vibe coding", "Typescript", "Netlify", "Firebase", "Supabase", "SQL"],
      "company": "Nextquark",
      "endDate": null,
      "workMode": "Remote",
      "isCurrent": true,
      "startDate": "Aug 2024",
      "description": "Built multiple AI products in AI space, started with LLM Security and Vulnerability Detection, after which pivoted to building AI voice Agents, and now finally building this super cool app, which is Tinder for Jobs!🩷",
      "jobLocation": "Remote",
      "employmentType": "Full-time"
    }
  ]'::jsonb,
  '[
    {
      "id": "1772580939420",
      "field": "Engineering Physics ",
      "degree": "Bachelor''s",
      "endDate": "2025",
      "startDate": "2020",
      "institution": "IIT BHU Varanasi "
    },
    {
      "id": "1772580955817",
      "field": "Engineering Physics ",
      "degree": "Master''s",
      "endDate": "2025",
      "startDate": "2020",
      "institution": "IIT BHU Varanasi "
    }
  ]'::jsonb,
  '[
    {
      "id": "c1772581229388",
      "name": "AWS Cloud Practitioner",
      "skills": ["AWS", "Cloud Computing"],
      "credentialUrl": "",
      "issuingOrganization": "AWD"
    }
  ]'::jsonb,
  '[
    {
      "id": "ach1772581131603",
      "date": "2024",
      "title": "IIT Color Award",
      "issuer": "IIT BHU Varanasi",
      "description": "Highest Distinction given to any student for extraordinary skills."
    }
  ]'::jsonb,
  '["Full-time", "Contract"]'::jsonb,
  ARRAY['On-site','Hybrid','Onsite'],
  'USD',
  NULL,
  480000,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  '{}'::jsonb,
  'Spacex',
  'Application Software Engineer',
  'https://job-boards.greenhouse.io/spacex/jobs/8211822002',
  'pending',
  '2026-03-06 02:06:10+05:30',
  'Dear Hiring Manager, I am excited to apply for this position. With my experience in software engineering and passion for space technology, I believe I would be a great fit for the SpaceX team. Best regards, Aditya Surana'
)
ON CONFLICT (id) DO UPDATE SET
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  company_name = EXCLUDED.company_name,
  job_title = EXCLUDED.job_title;
